    "m.sberbank.ru", "sber.ru", "sberbank.com", "sberbank.ru", "sbrf.ru",
    "www.sberbank.ru",

    "cdn-tinkoff.ru", "m.tbank.ru", "m.tinkoff.ru", "my-tbank.ru",
    "rosbank.ru", "t-bank-app.ru", "tbank.ru", "tcsbank.ru",
    "tinkoff.ru", "www.tbank.ru", "www.tinkoff.ru",

    "alfa.me", "alfabank.ru", "alfabank.st", "gazprombank.ru", "gpb.ru",
    "m.alfabank.ru", "m.gazprombank.ru", "m.psb.ru", "m.raiffeisen.ru", "m.vtb.ru",
    "psb.ru", "psbank.ru", "raiffeisen.ru", "vtb.ru",
    "www.alfabank.ru", "www.gazprombank.ru", "www.psb.ru", "www.raiffeisen.ru",
    "www.vtb.ru",

    "akbars.ru", "bspb.ru", "domrfbank.ru", "homecredit.ru", "mkb.ru",
    "m.mtsbank.ru", "m.rshb.ru", "m.sovcombank.ru",
    "mtsbank.ru", "otpbank.ru", "pochtabank.ru", "rencredit.ru", "rshb.ru",
    "sovcombank.ru", "tochka.com", "uralsib.ru",
    "www.mtsbank.ru", "www.rshb.ru", "www.sovcombank.ru",
