    "m.ozon.ru", "o3.ru", "ozon.ru", "ozonusercontent.com", "ozone.ru",
    "www.ozon.ru", "www.ozone.ru", "xapi.ozon.ru",
    "cdn1.ozonusercontent.com", "ir.ozone.ru",

    "m.wildberries.ru", "wb.ru", "wbbasket.ru", "wbcontent.net", "wbstatic.net",
    "wildberries.ru", "www.wildberries.ru",

    "auto.ru", "avito.ru", "avito.st", "cian.ru", "drom.ru",
    "m.auto.ru", "m.avito.ru", "m.cian.ru", "m.drom.ru",
    "www.auto.ru", "www.avito.ru", "www.cian.ru", "www.drom.ru",

    "avatars.mds.yandex.net", "disk.yandex.ru", "kinopoisk.ru", "mail.yandex.ru",
    "maps.yandex.ru", "maps.yastatic.net", "market.yandex.ru", "mc.yandex.ru",
    "music.yandex.ru", "passport.yandex.ru", "taxi.yandex.ru",
    "www.kinopoisk.ru", "www.ya.ru", "www.yandex.ru", "www.yastatic.net",
    "ya.ru", "yandex.net", "yandex.ru", "yastatic.net", "m.yandex.ru",

    "kuper.ru", "m.kuper.ru", "m.megamarket.ru", "m.samokat.ru",
    "megamarket.ru", "samokat.ru", "www.kuper.ru", "www.megamarket.ru",
    "www.samokat.ru",

    "esia.gosuslugi.ru", "gosuslugi.ru", "gu-st.ru", "mos.ru",
    "nalog.gov.ru", "nalog.ru", "www.gosuslugi.ru", "www.mos.ru",

    "ostrovok.ru", "pass.rzd.ru", "rzd.ru", "tutu.ru",
    "www.ostrovok.ru", "www.rzd.ru", "www.tutu.ru",
